version: '3'

services:

  prometheus:
    image: prom/prometheus
    container_name: aiops-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
